"""Add password_hash field

Revision ID: 585ff51d4d63
Revises: 
Create Date: 2025-10-21 18:38:02.205921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585ff51d4d63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('avatar')
        batch_op.drop_column('email_confirmed')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
